### ISSUE TITLE
巨大ファイル対応の影響 - Network上のファイルがアクセスできなくなった時に、いろいろおかしくなる

### ISSUE THREAD

**Issue by crftwr** [crftwr/lredit#4]
LREdit version :

Traceback (most recent call last):

  File ".\lredit_mainwindow.py", line 1395, in _onKeyDown

  File "../ckit\ckit_command.py", line 28, in __call__

  File ".\lredit_mainwindow.py", line 1983, in executeCommand

  File ".\lredit_mainwindow.py", line 4368, in command_Close

  File ".\lredit_mainwindow.py", line 2720, in _close

  File "../ckit\ckit_textwidget.py", line 1297, in destroy

  File "../ckit\ckit_textwidget.py", line 775, in removeReference

  File "../ckit\ckit_textwidget.py", line 760, in _destroy

  File "../ckit\ckit_misc.py", line 561, in unlock

FileNotFoundError: [WinError 2] The system cannot find the file specified.

Traceback (most recent call last):

  File ".\lredit_mainwindow.py", line 1395, in _onKeyDown

  File "../ckit\ckit_command.py", line 28, in __call__

  File ".\lredit_mainwindow.py", line 1983, in executeCommand

  File ".\lredit_mainwindow.py", line 4368, in command_Close

  File ".\lredit_mainwindow.py", line 2701, in _close

AttributeError: 'NoneType' object has no attribute 'isDiffColorMode'

Traceback (most recent call last):

  File ".\lredit_mainwindow.py", line 1395, in _onKeyDown

  File "../ckit\ckit_command.py", line 28, in __call__

  File ".\lredit_mainwindow.py", line 1983, in executeCommand

  File ".\lredit_mainwindow.py", line 4368, in command_Close

  File ".\lredit_mainwindow.py", line 2701, in _close

AttributeError: 'NoneType' object has no attribute 'isDiffColorMode'

Traceback (most recent call last):

  File ".\lredit_mainwindow.py", line 1395, in _onKeyDown

  File "../ckit\ckit_command.py", line 28, in __call__

  File ".\lredit_mainwindow.py", line 1983, in executeCommand

  File ".\lredit_mainwindow.py", line 4368, in command_Close

  File ".\lredit_mainwindow.py", line 2701, in _close

AttributeError: 'NoneType' object has no attribute 'isDiffColorMode'

Traceback (most recent call last):

  File ".\lredit_mainwindow.py", line 1395, in _onKeyDown

  File "../ckit\ckit_command.py", line 28, in __call__

  File ".\lredit_mainwindow.py", line 1983, in executeCommand

  File ".\lredit_mainwindow.py", line 4368, in command_Close

  File ".\lredit_mainwindow.py", line 2701, in _close

AttributeError: 'NoneType' object has no attribute 'isDiffColorMode'

**Comment by crftwr** [comment]
ファイルにアクセスできなくなったことを検出して、エラーを表示して、Documentを閉じる？

**Comment by crftwr** [comment]
巨大ファイル対応は64bit版をリリースすることで対応したことにする。
